import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { DB } from "../constants.js";
import { getNotion, makeReceipt, toRichText } from "../services/notion.js";

export function registerPatternTools(server: McpServer): void {

  server.registerTool("claudine_search_atlas",{title:"Search Notion Atlas",description:`Search the Claudine workspace for pages, databases, or content.`,inputSchema:z.object({query:z.string().min(2).max(200),filter_type:z.enum(["page","database"]).optional(),limit:z.number().int().min(1).max(25).default(10)}),annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},async({query,filter_type,limit})=>{const notion=getNotion();const searchParams:Parameters<typeof notion.search>[0]={query,page_size:limit};if(filter_type)searchParams.filter={value:filter_type,property:"object"};const response=await notion.search(searchParams);if(response.results.length===0)return{content:[{type:"text",text:`No results found for "${query}".`}],structuredContent:{results:[],count:0}};const results=response.results.map(item=>{const obj=item as Record<string,unknown>;const type=obj["object"]as string;let title="(untitled)";if(type==="page"){const props=obj["properties"]as Record<string,unknown>|undefined;if(props){const titleProp=Object.values(props).find((p)=>(p as Record<string,unknown>)["type"]==="title")as Record<string,unknown>|undefined;if(titleProp){const titleArr=titleProp["title"]as Array<{plain_text:string}>;title=titleArr.map(t=>t.plain_text).join("")||"(untitled)";}}}else if(type==="database"){const titleArr=obj["title"]as Array<{plain_text:string}>|undefined;title=titleArr?.map(t=>t.plain_text).join("")||"(untitled)";}return{id:obj["id"]as string,type,title,url:obj["url"]as string??`https://notion.so/${(obj["id"]as string).replace(/-/g,"")}`};});return{content:[{type:"text",text:JSON.stringify({results,count:results.length},null,2)}],structuredContent:{results,count:results.length}};});

  server.registerTool("claudine_log_pattern",{title:"Log Pattern",description:`Write a new pattern entry to the Pattern Language page. Use when a pattern crystallizes and is ready to be named. Contract v0.1: Pattern Language is a page not a database. Entries are appended as content blocks.`,inputSchema:z.object({name:z.string().min(3).max(100),description:z.string().min(20).max(2000),status:z.enum(["Observed","Validated","Load-bearing"]).default("Observed"),source_morph:z.enum(["AR","Bridge","Constellation","Repository","Crucible","Versailles","TYC","Track Two","Brunch Babies","Feral Claudine","La Fondation","Keeper","Non-morph"]),domain:z.string().optional()}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:false}},async({name,description,status,source_morph,domain})=>{const notion=getNotion();const date=new Date().toISOString().slice(0,10);const domainTag=domain?` | ${domain}`:"";await notion.blocks.children.append({block_id:DB.PATTERN_LANGUAGE,children:[{object:"block",type:"heading_3",heading_3:{rich_text:[{type:"text",text:{content:"---"}}]}},{object:"block",type:"paragraph",paragraph:{rich_text:[{type:"text",text:{content:`${name} | ${status} | ${source_morph}${domainTag} | ${date}`},annotations:{bold:true}}]}},{object:"block",type:"paragraph",paragraph:{rich_text:toRichText(description)}}]});const receipt=makeReceipt("log_pattern",DB.PATTERN_LANGUAGE,`https://notion.so/${DB.PATTERN_LANGUAGE.replace(/-/g,"")}`,{name,status,source_morph,domain:domain??null,date});return{content:[{type:"text",text:JSON.stringify(receipt,null,2)}],structuredContent:receipt};});

  server.registerTool("claudine_get_contract",{title:"Get Contract",description:`Return the current Notion Contract version and allowed surfaces.`,inputSchema:z.object({}),annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},async()=>{const contract={contract_version:"v0.1",writable_surfaces:[{name:"Session Deposits",id:DB.SESSION_DEPOSITS},{name:"Claudine Tasks",id:DB.CLAUDINE_TASKS},{name:"Living Sync",id:DB.LIVING_SYNC},{name:"Pattern Language",id:DB.PATTERN_LANGUAGE},{name:"Messages",id:DB.MESSAGES},{name:"Signal Board",id:DB.SIGNAL_BOARD||"(not configured)"}],read_only_surfaces:[{name:"Architecture Hub",id:DB.ARCHITECTURE_HUB}],frozen_properties:{session_deposits:["Deposit","Content","Source Morph","Owner morph","Confidence","Type","Status","State","Destination","Session Date"],claudine_tasks:["Task","Status","Priority","Domain","Triage","Notes","Due","Source"],living_sync_anchors:["## Current System Context","## ⚡ Quick Dispatch","## Quick Links"]},signal_board_configured:!!DB.SIGNAL_BOARD,pulse_archive_configured:!!DB.PULSE_ARCHIVE};return{content:[{type:"text",text:JSON.stringify(contract,null,2)}],structuredContent:contract};});

  server.registerTool("claudine_healthcheck",{title:"Healthcheck",description:`Verify Notion API token and critical surfaces are reachable.`,inputSchema:z.object({}),annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},async()=>{const notion=getNotion();const surfaces=[{name:"Session Deposits",id:DB.SESSION_DEPOSITS,type:"database"},{name:"Claudine Tasks",id:DB.CLAUDINE_TASKS,type:"database"},{name:"Living Sync",id:DB.LIVING_SYNC,type:"page"},{name:"Architecture Hub",id:DB.ARCHITECTURE_HUB,type:"page"}];const results=await Promise.all(surfaces.map(async s=>{try{if(s.type==="database"){await notion.databases.retrieve({database_id:s.id});}else{await notion.pages.retrieve({page_id:s.id});}return{surface:s.name,status:"ok"};}catch(error){return{surface:s.name,status:"error",error:String(error)};}}));const summary={healthy:results.every(r=>r.status==="ok"),contract_version:"v0.1",signal_board_configured:!!DB.SIGNAL_BOARD,pulse_archive_configured:!!DB.PULSE_ARCHIVE,surfaces:results};return{content:[{type:"text",text:JSON.stringify(summary,null,2)}],structuredContent:summary};});

  server.registerTool("claudine_get_pulse_summary",{title:"Get Pulse Summary",description:`Read the most recent Pulse report from the Pulse Archive database. Requires PULSE_ARCHIVE_DB_ID.`,inputSchema:z.object({limit:z.number().int().min(1).max(5).default(1)}),annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},async({limit})=>{if(!DB.PULSE_ARCHIVE)return{content:[{type:"text",text:"Pulse Archive not configured. Set PULSE_ARCHIVE_DB_ID."}],structuredContent:{reports:[],count:0}};const notion=getNotion();const response=await notion.databases.query({database_id:DB.PULSE_ARCHIVE,sorts:[{timestamp:"created_time",direction:"descending"}],page_size:limit});if(response.results.length===0)return{content:[{type:"text",text:"No Pulse reports found."}],structuredContent:{reports:[],count:0}};const reports=response.results.map(page=>{const obj=page as Record<string,unknown>;const props=obj["properties"]as Record<string,unknown>;const titleProp=Object.values(props).find(p=>(p as Record<string,unknown>)["type"]==="title")as Record<string,unknown>|undefined;const title=titleProp?(titleProp["title"]as Array<{plain_text:string}>).map(t=>t.plain_text).join(""):"(untitled)";return{id:obj["id"]as string,title,url:obj["url"]as string,created:(obj as{created_time?:string}).created_time};});return{content:[{type:"text",text:JSON.stringify({reports,count:reports.length},null,2)}],structuredContent:{reports,count:reports.length}};});
}
